### ISSUE TITLE
cannot install on VSCodium, Kubuntu

### ISSUE THREAD

**Issue by aosi87** [leodevbro/vscode-blockman#46]
Bug: Looks like there is an issue or validation when trying to install this using the open source version of VS Code.

`Unable to install "leodevbro.blockman" extension because is not compatible with the current version of VS Code (Version 1.56.0)`

the window console:

```
[2021-10-13 16:31:50.377] [renderer3] [error] ["incompatible: Unable to install 'leodevbro.blockman' extension because it is not compatible with the current version of VS Code (version 1.56.0).","    at H.checkAndGetCompatibleVersion (file:///snap/codium/166/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:215682)","
at async H.installFromGallery (file:///snap/codium/166/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:213343)"]

[2021-10-13 16:31:50.385] [renderer3] [error] Unable to install 'leodevbro.blockman' extension because it is not compatible with the current version of VS Code (version 1.56.0).: incompatible: Unable to install 'leodevbro.blockman' extension because it is not compatible with the current version of VS Code (version 1.56.0).
    at H.checkAndGetCompatibleVersion (file:///snap/codium/166/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:215682)
    at async H.installFromGallery (file:///snap/codium/166/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:213343)
```

I'm pretty sure there shouldn't be any incompatibility here so my best guess is that the validation has a logic issue.

**Comment by leodevbro** [comment]
As I can see, your VSCode version is `1.56.0`, Blockman supports version `1.56.1` and newer. Please try to update VSCode/VSCodium.

**Comment by leodevbro** [comment]
Thanks, I hope Blockman will work fine in your environent.
