### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by lachieh** [leodevbro/vscode-blockman#8]
Hey there! thanks for building this!

I'm having an issue with the latest version of the extension (1.1.4) and VSCode (1.56.2) where the extension will not load. 
I've attached the log below. Happy to provide anything else if it helps you debug further.

```
[2021-06-09 20:36:14.502] [exthost] [info] ExtensionService#_doActivateExtension leodevbro.blockman {"startup":false,"extensionId":{"value":"leodevbro.blockman","_lower":"leodevbro.blockman"},"activationEvent":"onStartupFinished"}
[2021-06-09 20:36:14.502] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/lachlanheywood/.vscode/extensions/leodevbro.blockman-1.1.4/out/extension.js
[2021-06-09 20:36:15.085] [exthost] [error] Activating extension leodevbro.blockman failed due to an error:
[2021-06-09 20:36:15.085] [exthost] [error] Error: Cannot invoke loadWASM more than once.
    at Object.t.loadWASM (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-oniguruma/release/main.js:1:4823)
    at TextMateLoader.loadOniguruma (/Users/~~/.vscode/extensions/leodevbro.blockman-1.1.4/out/bracketAlgos/textMateLoader.js:122:19)
    at new TextMateLoader (/Users/~~/.vscode/extensions/leodevbro.blockman-1.1.4/out/bracketAlgos/textMateLoader.js:21:31)
    at new Settings (/Users/~~/.vscode/extensions/leodevbro.blockman-1.1.4/out/bracketAlgos/settings.js:10:31)
    at new DocumentDecorationManager (/Users/~~/.vscode/extensions/leodevbro.blockman-1.1.4/out/bracketAlgos/documentDecorationManager.js:10:25)
    at activate (/Users/~~/.vscode/extensions/leodevbro.blockman-1.1.4/out/extension.js:747:30)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:14813)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:14486)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:12643
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

```

It also shows an error when I attempt the 'Toggle Enable/Disable' command. Not sure if this is related, or if it is a result of the extension failing to load, but here's that error also:
```
Command 'Blockman Toggle Enable/Disable' resulted in an error (command 'blockman.toggleEnableDisable' not found)
```

**Comment by leodevbro** [comment]
Hi, maybe there is a conflict to another extension, possibly to Bracket Pair Colorizer 2 (1 works fine, but 2 has conflicts sometimes). You can try uninstalling BPC2, and restart VSCode. Currently I'm searching for the cause of such conflicts.

**Comment by leodevbro** [comment]
Hello again, check out this page
https://github.com/CoenraadS/CoenraadS/issues/1
As I see, the solution is to just update VSCode to the latest version.

**Comment by lachieh** [comment]
Confirmed that updating to latest version of VSCode (1.57.0) solves this problem. Thanks, @leodevbro!

**Comment by holoubl** [comment]
**Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No**

A have tha same issue

**Comment by leodevbro** [comment]
@holoubl, I have the same version (`1.72.2`) of VS Code, and Blockman loads fine. Please try restarting VS Code, maybe twice.

**Comment by holoubl** [comment]
Restarted many times. no effect. I believe to some collision with another extension. But which?

**Comment by leodevbro** [comment]
Please try downgrading Blockman to `1.5.9` version and check whether it works or not. If it works, then the update maybe broke something.

![image](https://user-images.githubusercontent.com/54504880/199522271-eee7aaa1-8938-4334-baa6-2bae9604bd3b.png)

**Comment by holoubl** [comment]
Even version 1.5.9 does not work.
but I noticed this box around the code:
![obrazek](https://user-images.githubusercontent.com/97892136/199570831-419fb90b-9f9c-44a9-bc58-e9857bdbe122.png)
The box must be from blockman because after dissabling block man, it disapers. So block man works, but not correctly.

**Comment by leodevbro** [comment]
Please show me the settings json files of `User` and `Workspace`.
![image](https://user-images.githubusercontent.com/54504880/199612556-dc5cafda-ec1d-48b4-8aee-7b7f1f0193fd.png)

**Comment by leodevbro** [comment]
Also, let's move back to this new issue:
https://github.com/leodevbro/vscode-blockman/issues/93

Because your problem seems different.
